export {
  MIDSTORY_TRIGGERS_BY_CLASS,
  MIDSTORY_TRIGGERS_CLK,
  MIDSTORY_TRIGGERS_SREL,
  MIDSTORY_TRIGGERS_STENT,
  MIDSTORY_TRIGGERS_STQ,
  MIDSTORY_TRIGGERS_STSEC,
  MIDSTORY_TRIGGERS_THR
} from "@worldloom/world-index/parse/intro-tag-parser";
