export const MCP_TOOL_NAMES = {
  search_nodes: "mcp__worldloom__search_nodes",
  get_node: "mcp__worldloom__get_node",
  get_record: "mcp__worldloom__get_record",
  get_records: "mcp__worldloom__get_records",
  get_records_field: "mcp__worldloom__get_records_field",
  get_story_state_provenance: "mcp__worldloom__get_story_state_provenance",
  verify_pg_state_hash: "mcp__worldloom__verify_pg_state_hash",
  get_persisted_packet_slice: "mcp__worldloom__get_persisted_packet_slice",
  list_records: "mcp__worldloom__list_records",
  get_record_field: "mcp__worldloom__get_record_field",
  get_record_schema: "mcp__worldloom__get_record_schema",
  get_neighbors: "mcp__worldloom__get_neighbors",
  get_context_packet: "mcp__worldloom__get_context_packet",
  find_impacted_fragments: "mcp__worldloom__find_impacted_fragments",
  find_sections_touched_by: "mcp__worldloom__find_sections_touched_by",
  find_named_entities: "mcp__worldloom__find_named_entities",
  find_edit_anchors: "mcp__worldloom__find_edit_anchors",
  get_canonical_vocabulary: "mcp__worldloom__get_canonical_vocabulary",
  validate_patch_plan: "mcp__worldloom__validate_patch_plan",
  submit_patch_plan: "mcp__worldloom__submit_patch_plan",
  plan_story_state_maintenance: "mcp__worldloom__plan_story_state_maintenance",
  allocate_next_id: "mcp__worldloom__allocate_next_id",
  allocate_many_ids: "mcp__worldloom__allocate_many_ids",
  get_firewall_content: "mcp__worldloom__get_firewall_content",
  describe_capabilities: "mcp__worldloom__describe_capabilities",
  describe_envelope_schema: "mcp__worldloom__describe_envelope_schema",
  select_storylet_candidates: "mcp__worldloom__select_storylet_candidates"
} as const;

export type ToolKey = keyof typeof MCP_TOOL_NAMES;
export type McpToolName = (typeof MCP_TOOL_NAMES)[ToolKey];

export const MCP_TOOL_ORDER: McpToolName[] = [
  MCP_TOOL_NAMES.search_nodes,
  MCP_TOOL_NAMES.get_node,
  MCP_TOOL_NAMES.get_record,
  MCP_TOOL_NAMES.get_records,
  MCP_TOOL_NAMES.get_records_field,
  MCP_TOOL_NAMES.get_story_state_provenance,
  MCP_TOOL_NAMES.verify_pg_state_hash,
  MCP_TOOL_NAMES.get_persisted_packet_slice,
  MCP_TOOL_NAMES.list_records,
  MCP_TOOL_NAMES.get_record_field,
  MCP_TOOL_NAMES.get_record_schema,
  MCP_TOOL_NAMES.get_neighbors,
  MCP_TOOL_NAMES.get_context_packet,
  MCP_TOOL_NAMES.find_impacted_fragments,
  MCP_TOOL_NAMES.find_sections_touched_by,
  MCP_TOOL_NAMES.find_named_entities,
  MCP_TOOL_NAMES.find_edit_anchors,
  MCP_TOOL_NAMES.get_canonical_vocabulary,
  MCP_TOOL_NAMES.validate_patch_plan,
  MCP_TOOL_NAMES.submit_patch_plan,
  MCP_TOOL_NAMES.plan_story_state_maintenance,
  MCP_TOOL_NAMES.allocate_next_id,
  MCP_TOOL_NAMES.allocate_many_ids,
  MCP_TOOL_NAMES.get_firewall_content,
  MCP_TOOL_NAMES.describe_capabilities,
  MCP_TOOL_NAMES.describe_envelope_schema,
  MCP_TOOL_NAMES.select_storylet_candidates
];
