export const CAPITALIZED_MULTIWORD_STOPLIST = new Set<string>([
  "The Maker",
  "The Makers",
  "A Certain",
  "Once Upon",
  "Access Path",
  "Action Report",
  "Age Details",
  "Breakage Point",
  "Breakage Points",
  "Canon Safety Check Trace",
  "Change Log Entry",
  "Continuity Archivist",
  "Count Specifics",
  "Core Pressures",
  "Distribution Discipline",
  "Fee Wage Schedule",
  "Genre Contract",
  "Inequality Patterns",
  "Mystery Curator",
  "Mystery Reserve",
  "Natural Story Engines",
  "No Silent Retcons",
  "Primary Difference",
  "Primary Rule",
  "Regional Asymmetry",
  "Required Updates",
  "Repairs Applied",
  "Ruin Ownership",
  "Tier Finder",
  "Trade Flows",
  "Tone Contract",
  "Truth Check",
  "Value Stores",
  "World Laundering"
]);

export function isStoplistedEntityCandidate(candidate: string): boolean {
  return CAPITALIZED_MULTIWORD_STOPLIST.has(candidate.trim());
}
